#!/usr/bin/env python3
import a2s
import sys
import os

"""
Munin plugin to query Valve SRCDS servers via anonymous a2s info queries (like in server browser).

Requires the a2s plugin: pip3 install python-a2s

Munin configuration example:
[srcds]
env.ip 127.0.0.1
env.port 27015
"""

server_ip = "127.0.0.1"
server_port = 27015
if "serverip" in os.environ:
  server_ip = os.environ['serverip']
if "serverport" in os.environ:
  server_port = int(os.environ['serverport'])

if len(sys.argv) > 1 and sys.argv[1] == "config":
  conf="""graph_title {} SRCDS Server Query
graph_vlabel Number of Players
graph_category projects
graph_printf %6.0lf
server_players.label Players
server_bots.label Bots
server_players.min 0
server_bots.min 0"""
  print(conf.format(server_ip))
else:
  address = (server_ip, server_port)
  try:
    query_results = a2s.info(address)
    num_players = query_results.player_count
    num_bots = query_results.bot_count
    out = """server_players.value {}
server_bots.value {}"""
    print(out.format(num_players, num_bots))
  except Exception as e:
    out = """server_players.value U
server_bots.value U"""
    print(out)
